const { hashMap } = require("./hashMap");

const myHashMap = new hashMap();
myHashMap.set("Tom", "I know he did the wrong thing");
myHashMap.set("Tom", "but");
myHashMap.set("Tom", "he putting career over his life");
myHashMap.set("Tom", "is something I also choose");

myHashMap.set("Jimmy", "Me too!!!");
myHashMap.set("Carla", "TOP is the best community to learn web!!!");
myHashMap.set("Carlos", "Carla is right");
console.log("Carla's information: " + myHashMap.get("Carla"));
console.log("is Jack has information in here: " + myHashMap.has("Jack"));
console.log("============");
myHashMap.display();
myHashMap.remove("Carla");
console.log("============");
myHashMap.display();
console.log("current occupation in hash map: " + myHashMap.length());
console.log(myHashMap.keys());
console.log(myHashMap.values());
console.log(myHashMap.entries());
myHashMap.set("Jack", "I ");
myHashMap.set("Jessica", "am");
myHashMap.set("Walter", "over");
myHashMap.set("Cook", "weight");
myHashMap.set("Timberland", "weight");
myHashMap.set("Json", "weight");
myHashMap.set("the Rock", "weight");
myHashMap.set("Anna", "weight");
myHashMap.set("Tim", "weight");
myHashMap.set("Henry", "weight");
myHashMap.set("Ben", "weight");
myHashMap.set("Lisa", "weight");
myHashMap.set("Jean", "weight");
myHashMap.set("Klee", "weight");
myHashMap.set("Kayak", "weight");
myHashMap.set("Beatriz", "weight");
myHashMap.set("Charles", "weight");
myHashMap.set("Eric", "weight");
myHashMap.set("Fatima", "weight");
myHashMap.set("Gabriel", "weight");
myHashMap.set("Hanna", "weight");
